{% set name = "wtfis" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wtfis-{{ version }}.tar.gz
  sha256: e3df5b8151b87e23e3f803be22739d6b7204e2c1f9460f773b85e38b81250efc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - wtfis = wtfis.main:main

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - pydantic ~=2.9.2
    - python >={{ python_min }}
    - python-dotenv ~=1.0.1
    - requests ~=2.32.3
    - rich ~=13.7.1
    - shodan ~=1.31.0

test:
  source_files:
    - tests
  imports:
    - wtfis
  commands:
    - pip check
    - export VT_API_KEY=foo
    - wtfis --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - freezegun
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/pirxthepilot/wtfis
  summary: Passive host and domain name lookup tool for non-robots
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - pirxthepilot
    - thewchan
