{% set name = "wtfis" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wtfis-{{ version }}.tar.gz
  sha256: d09252f911635a073bcc00e0fdf304663f076cb90ced3d8a2742b5eaabcaa84a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - wtfis = wtfis.main:main

requirements:
  host:
    - hatchling
    - pip
    - python >=3.8
  run:
    - pydantic ~=1.10.2
    - python >=3.8
    - python-dotenv ~=0.21.0
    - requests ~=2.28.1
    - rich ~=12.6.0
    - shodan ~=1.28.0

test:
  source_files:
    - tests
  imports:
    - wtfis
  commands:
    - pip check
    - export VT_API_KEY=foo
    - wtfis --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - freezegun
    - pip
    - pytest

about:
  home: https://github.com/pirxthepilot/wtfis
  summary: Passive host and domain name lookup tool for non-robots
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - pirxthepilot
    - thewchan
