{% set name = "wtfis" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wtfis-{{ version }}.tar.gz
  sha256: e5922c6550488e90e8a6e19805f0432a607155f27edcb75f1a43e5152e72a197

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - wtfis = wtfis.main:main

requirements:
  host:
    - hatchling
    - pip
    - python >=3.8
  run:
    - pydantic ~=2.0.3
    - python >=3.8
    - python-dotenv ~=1.0.0
    - requests ~=2.31.0
    - rich ~=13.4.2
    - shodan ~=1.29.1

test:
  source_files:
    - tests
  imports:
    - wtfis
  commands:
    - pip check
    - export VT_API_KEY=foo
    - wtfis --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - freezegun
    - pip
    - pytest

about:
  home: https://github.com/pirxthepilot/wtfis
  summary: Passive host and domain name lookup tool for non-robots
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - pirxthepilot
    - thewchan
