{% set name = "wtfis" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wtfis-{{ version }}.tar.gz
  sha256: c3c0d3ef1fef20222bc3cb96f2b69a00e9714e468277fd87cf20c051de253331

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - wtfis = wtfis.main:main

requirements:
  host:
    - hatchling
    - pip
    - python >=3.8
  run:
    - pydantic ~=2.7.2
    - python >=3.8
    - python-dotenv ~=1.0.1
    - requests ~=2.32.3
    - rich ~=13.7.1
    - shodan ~=1.31.0

test:
  source_files:
    - tests
  imports:
    - wtfis
  commands:
    - pip check
    - export VT_API_KEY=foo
    - wtfis --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - freezegun
    - pip
    - pytest

about:
  home: https://github.com/pirxthepilot/wtfis
  summary: Passive host and domain name lookup tool for non-robots
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - pirxthepilot
    - thewchan
